'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("REFORDS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4710x2919__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4710x2919__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property affogato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("affogato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aloo_matar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aloo matar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aloo_palak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aloo palak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aloobonda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aloobonda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ambadivilas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ambadivilas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baileyscoffee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baileyscoffee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bamboo_wok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bamboo wok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banghancurry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banghancurry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property biella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("biella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property biryanibhaat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("biryanibhaat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blackminttea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackminttea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blacktea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacktea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueberrycrepes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueberrycrepes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boogiwoogiball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boogiwoogiball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cafefrape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cafefrape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chana_Masala_loose_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chana_Masala_loose_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chatsamosa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chatsamosa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chef() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chef", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cherrynoodles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cherrynoodles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chikenkabab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chikenkabab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chinesechikenfeet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinesechikenfeet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chocoballs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chocoballs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chococherry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chococherry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chocochocobowl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chocochocobowl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chococubsberry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chococubsberry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property choconuts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("choconuts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chowmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chowmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coldlemontea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coldlemontea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property constispicyfood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("constispicyfood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crab_tandoor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crab tandoor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crabgarlic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crabgarlic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crabmasala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crabmasala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cremaexpresso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cremaexpresso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crispfry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crispfry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property curtesybelesaru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curtesybelesaru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property curtesyyummy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curtesyyummy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dahikachori() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dahikachori", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dal_makhani1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dal-makhani1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dalkachori() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dalkachori", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dosa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dosa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dryfruitsamosa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dryfruitsamosa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dumpling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dumpling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eggmasala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eggmasala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eggroll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eggroll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property expressomachiato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expressomachiato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flatwhitecoffee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flatwhitecoffee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property foodfishsushi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foodfishsushi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property form1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gingertea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gingertea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greentea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greentea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icecreamberryroll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icecreamberryroll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icecreamcusturd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icecreamcusturd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icecreamnapkin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icecreamnapkin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property idlisambhar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idlisambhar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italiancuisine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italiancuisine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italiandonut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italiandonut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jeera_aloo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jeera aloo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kadai_paneer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kadai paneer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keema() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keema", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property latte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("latte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lobster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lobster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property masala_bhendi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("masala bhendi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property masaltea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("masaltea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property milktea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("milktea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mintlemontea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mintlemontea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mochalatte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mochalatte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mushroom_mutter_curry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mushroom mutter curry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noodles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noodles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noodoprawns() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noodoprawns", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olivepizza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olivepizza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oniomasala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oniomasala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property onionkachori() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onionkachori", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property originalturkish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("originalturkish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pasta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pastamacrony() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pastamacrony", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pastapeas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pastapeas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pastasausages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pastasausages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property planelemontea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("planelemontea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prawncurry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prawncurry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prawnstandoor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prawnstandoor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property promfitchilli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("promfitchilli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rostedpieces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rostedpieces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sambharwada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sambharwada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sambharwada1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sambharwada1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shellnoodels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shellnoodels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property soupypirhana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soupypirhana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property soupyturtle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soupyturtle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property southcuisine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("southcuisine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property special_thali() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("special thali", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property squidgoldenfry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("squidgoldenfry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property squidsaltpepper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("squidsaltpepper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strawberrytea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strawberrytea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tadka_dal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tadka dal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uttapam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uttapam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vanilla_waffy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vanilla waffy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property westincontifood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("westincontifood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wienermielange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wienermielange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
